# Generated by Django 2.2 on 2019-12-30 06:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('name', models.CharField(max_length=100, verbose_name='chapter name')),
                ('learning_time', models.IntegerField(default=0, verbose_name='learning time in seconds')),
            ],
            options={
                'verbose_name': 'chapter information',
                'verbose_name_plural': 'chapter information',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('name', models.CharField(max_length=50, verbose_name='course name')),
                ('desc', models.CharField(max_length=300, verbose_name='course description')),
                ('learning_time', models.IntegerField(default=0, verbose_name='learning time in seconds')),
                ('degree', models.CharField(choices=[('junior', 'junior'), ('mid', 'mid'), ('senior', 'senior')], max_length=6, verbose_name='course difficulty')),
                ('students', models.IntegerField(default=0, verbose_name='number of students')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='number of favorites')),
                ('click_nums', models.IntegerField(default=0, verbose_name='number of clicks')),
                ('category', models.CharField(default='backend development', max_length=20, verbose_name='course category')),
                ('tag', models.CharField(default='', max_length=10, verbose_name='course tag')),
                ('you_need_know', models.CharField(default='', max_length=300, verbose_name='course instruction')),
                ('teacher_tell', models.CharField(default='', max_length=300, verbose_name="teacher's introduction")),
                ('detail', models.TextField(verbose_name='course detail')),
                ('image', models.ImageField(upload_to='course/%Y/%m', verbose_name='course image')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Teacher', verbose_name='course lecturer')),
            ],
            options={
                'verbose_name': 'course information',
                'verbose_name_plural': 'course information',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('name', models.CharField(max_length=100, verbose_name='lesson name')),
                ('learning_time', models.IntegerField(default=0, verbose_name='learning time in seconds')),
                ('url', models.CharField(max_length=200, verbose_name='video link')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Chapter', verbose_name='lesson')),
            ],
            options={
                'verbose_name': 'video information',
                'verbose_name_plural': 'video information',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('name', models.CharField(max_length=100, verbose_name='resource name')),
                ('file', models.FileField(upload_to='course/resource/%Y/%m', verbose_name='resource download link')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'course resource',
                'verbose_name_plural': 'course resource',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
